//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NextItemBuy.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public int Budget { get; set; }
        public bool IsIncome { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    }
}
